name: Deploy for production

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: pulpoar
  REPOSITORY: skingpt-example
  GAR_LOCATION: europe-west3
  REGION: europe-west3
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_DEPLOYMENT_MANAGER_KEY }}
          token_format: 'access_token'

      - name: Docker Auth
        uses: 'docker/login-action@v2'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: _json_key
          password: ${{ secrets.GCP_DEPLOYMENT_MANAGER_KEY }}

      - name: Docker Build
        run: docker build -f Dockerfile -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY }}:${{ env.BRANCH_NAME }} ./

      - name: Docker Push
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY }}:${{ env.BRANCH_NAME }}

      - name: Deploy to Cloud Run
        id: deploy-api
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.REPOSITORY }}-${{ env.BRANCH_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY }}:${{ env.BRANCH_NAME }}
          flags: --port=3000 --allow-unauthenticated --min-instances=1 --max-instances=10 --cpu=2 --memory=4Gi --cpu-boost --no-cpu-throttling --execution-environment=gen2

